name: Build & Deploy
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build with NodeJS
        run: |
          npm i
          npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Ziedelth.fr
          path: ./dist/
